# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Trigger Local Jenkins
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS
    steps:
    - name: Trigger Shell script to trigger Jenkins job
      run: ~/github-actions.sh
