# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS
    steps:
    - name: Trigger Jenkins Webhook
      uses: appleboy/jenkins-action@master
      with:
        url: "http://localhost:8080"
        user: "gowthamraj07"
        token: "11ca13be67e3954c2f03a81456b1834661"
        job: "Android-CI-CD-POC"
